name: CI

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main
    - release

jobs:
  build:
    name: CI - ${{ matrix.name }}
    runs-on: ${{ matrix.runner-os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x86_64
            runner-os: windows-latest

          - name: Windows aarch64
            runner-os: windows-11-arm

          - name: Linux x86_64
            runner-os: ubuntu-22.04

          - name: Linux aarch64
            runner-os: ubuntu-22.04-arm

          - name: macOS aarch64
            runner-os: macos-15

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Restore Rust Cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ matrix.runner-os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --locked --verbose

    - name: Test
      run: cargo test --locked --verbose

    - name: Save Rust Cache
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ matrix.runner-os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

  msrv:
    name: Check MSRV
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Rust
      uses: dtolnay/rust-toolchain@1.88.0

    - name: Restore Rust Cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --locked --verbose

    - name: Save Rust Cache
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Restore Rust Cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Setup Rokit
      uses: CompeyDev/setup-rokit@v0.1.2
      with:
        version: 'v1.1.0'

    - name: Stylua
      run: stylua --check plugin/src

    - name: Selene
      run: selene plugin/src

    - name: Rustfmt
      run: cargo fmt -- --check

    - name: Clippy
      run: cargo clippy

    - name: Save Rust Cache
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
